export const QUIZ_TRANSLATIONS = {
    NO_RESPONSE_FOR_NOW: 'NO_RESPONSE_FOR_NOW',
    NO_DATA_FOR_GENERAL_CHARTS: 'NO_DATA_FOR_GENERAL_CHARTS',
    ATTEMPTS_PROGRESS_NUMBER_OF_ATTEMPTS: 'ATTEMPTS_PROGRESS_NUMBER_OF_ATTEMPTS',
    CREATE_VIEW_NUMBER_OF_ATTEMPTS: 'CREATE_VIEW_NUMBER_OF_ATTEMPTS',
    MULTIPLE_CHOICE_NOT_CORRECT: 'MULTIPLE_CHOICE_NOT_CORRECT',
} as const