export const QUIZ_TRANSLATIONS = {
  NO_RESPONSE_FOR_NOW: 'NO_RESPONSE_FOR_NOW',
  NO_DATA_FOR_GENERAL_CHARTS: 'NO_DATA_FOR_GENERAL_CHARTS',
  ATTEMPTS_PROGRESS_NUMBER_OF_ATTEMPTS: 'ATTEMPTS_PROGRESS_NUMBER_OF_ATTEMPTS',
  CREATE_VIEW_NUMBER_OF_ATTEMPTS: 'CREATE_VIEW_NUMBER_OF_ATTEMPTS',
  MULTIPLE_CHOICE_NOT_CORRECT: 'MULTIPLE_CHOICE_NOT_CORRECT',
  HINTS_TITLE: 'HINTS_TITLE',
  HINTS_SUB_TITLE: 'HINTS_SUB_TITLE',
  HINTS_LABEL: 'HINTS_LABEL',
  HINTS_ALERT_TITLE: 'HINTS_ALERT_TITLE',
} as const;
